version: "3"
containers:
- name: master-server
  image: gcr.io/instruqt-images-330918/java8base:1.0
  shell: /bin/bash
  memory: 1024
- name: data-server-1
  image: gcr.io/instruqt-images-330918/java8base:1.0
  shell: /bin/bash
  memory: 2048
- name: data-server-2
  image: gcr.io/instruqt-images-330918/java8base:1.0
  shell: /bin/bash
  memory: 2048
- name: query-server
  image: gcr.io/instruqt-images-330918/java8base:1.0
  shell: /bin/bash
  memory: 1024
