#!/bin/bash

echo "Starting Druid"

wget https://dlcdn.apache.org/druid/25.0.0/apache-druid-25.0.0-bin.tar.gz
tar -xzf apache-druid-25.0.0-bin.tar.gz
nohup /root/apache-druid-25.0.0/bin/start-nano-quickstart > /root/log.out 2> /root/log.err < /dev/null & disown
sleep 1
