#!/bin/bash

echo "Starting Druid"

wget https://dlcdn.apache.org/druid/24.0.2/apache-druid-24.0.2-bin.tar.gz
tar -xzf apache-druid-24.0.2-bin.tar.gz
nohup /root/apache-druid-24.0.2/bin/start-nano-quickstart > /root/log.out 2> /root/log.err < /dev/null & disown
sleep 1
